Adds contributing guide and CoD
icebreakerone/perseus-demo-energy pull request #38
Opened 2024-07-29 09:38 UTC by kipparker

It may be worth adding a contributing guide, I've created this from the boiler plate at https://contributing.md (seems very widely used), editing it for brevity and adding our details. The short version is:

- Enhancements / improvement / bugs as GitHub issues
- Ask or help in the Slack channel
- Security issues via email

Alternatively we could add details of this to the README.md. 

I've included the code of conduct from contributing.md without edits, but it might be less appropriate for a project like this.

2024-07-30 15:59 UTC, kipparker commented on CONTRIBUTING.md
> +A slack channel is available for participants building prototypes for the Perseus trust framework pilot, and is the best place to ask questions. If you are not part of the slack channel and wish to h
Participants are guided to the Slack channel to ask questions

2024-07-30 15:59 UTC, kipparker commented on CONTRIBUTING.md
> +If you then still feel the need to ask a question and need clarification, we recommend the following:
Other users are guided to github issues to ask questions

2024-07-30 15:59 UTC, kipparker commented on CONTRIBUTING.md
> +
Note that security issues should not be raised as issues, but sent as emails

2024-07-30 15:59 UTC, kipparker commented on CONTRIBUTING.md
> +Feedback on our documentation is always welcome. If you see something that is wrong, missing, or could be explained better, you can help us by creating an issue, or by creating a pull request with th
Not sure if we should put something about other channels for comments on documentation? Thinking that anyone reading this is probably a github user, so will be able to deal with raising issues / pull requests

2024-07-31 15:35 UTC, bensummers commented on CODE_OF_CONDUCT.md
> +reported to the community leaders responsible for enforcement at .
Missing email address or means of communication.

2024-07-31 15:37 UTC, bensummers requested changes
Just need to fill in a missing bit of data. Text feels quite standard, as you'd expect from a generator.

2024-07-31 16:26 UTC, merged